version: '3.8'

services:

  label-studio:
    image: heartexlabs/label-studio:latest
    ports:
      - 8080:8080
    volumes:
      - ./label-studio_data:/label-studio/data
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
